### ISSUE TITLE
Write User Stories

### ISSUE THREAD

**Issue by mariobehling** [fossasia/CommonsNet#1]
Please write user stories and add them to the Google doc.

**Comment by agwisniewska** [comment]
The user stories which I have written were added to Google doc.

**Comment by mariobehling** [comment]
https://docs.google.com/document/d/1nCPwxf1InfSjV3LQN-1zVhuoHcJ3HfUuPQMva4G8iII/edit#heading=h.69vjatmra17s

**Comment by agwisniewska** [comment]
I think it's finished and can be closed.
