### ISSUE TITLE
Add EditorConfig configuration to improve code style consistency

### ISSUE THREAD

**Issue by tkryskiewicz** [fossasia/CommonsNet#117]
Please add [EditorConfig](http://editorconfig.org/) configuration file and mention it to potential contributors.

Also install plugin for your editor of choice (ist available on EditorConfig website).

My recommended settings are:
```
root = true

[*]
charset = utf-8

indent_style = space
indent_size = 2

end_of_line = lf
trim_trailing_whitespace = true

insert_final_newline = true

[*.md]
insert_final_newline = false
trim_trailing_whitespace = false
```

Currently it's a mix of 2, 4, 6 spaces and tabs. Code should be refactored with time to be consistent.

**Comment by agwisniewska** [comment]
https://github.com/fossasia/CommonsNet/pull/118
