### ISSUE TITLE
Move static text to resources

### ISSUE THREAD

**Issue by tkryskiewicz** [fossasia/CommonsNet#120]
Please move static text from templates/partials and scripts to a localization file, so it's easier to work with markup and so that it don't obfuscate the code. Also localization would be much easier.

A useful tool for that is [angular-translate](https://github.com/angular-translate/angular-translate). There's also a [Guide](https://angular-translate.github.io/docs/#/guide) available.

In markup:
```
<label for="password">WIFI Password</label>
```
can be:
```
<label for="password">
  {{'wifi.details.password' | translate}}
</label>
```

In scripts:
```
{
  subtitle: 'BASIC DETAILS',
  ...
}
```
can be:
```
{
  subtitle: 'about.basic_details.title',
  ...
}
```
and in `appInfo.html`:
```
<h3 class="hcon"><b> {{ info.title | translate }} <b> </h3> 
```

**Comment by agwisniewska** [comment]
I think this part is done. All static texts are moved to local-en.json
