### ISSUE TITLE
Preparing structure of a file (.fodt) and make it editable

### ISSUE THREAD

**Issue by agwisniewska** [fossasia/CommonsNet#17]
#6  #21 
Based on user's data  from wizard form we need to generate pdf file which will consist of four sections like in wizard form and all provided details.

**Comment by agwisniewska** [comment]
The initial versionworks. but still needs to be improved and developed etc.
https://commonsnet.herokuapp.com/#/generate-wifi To test it, please fill  form first and then click SAVE button. The file should be opened in other window

**Comment by tabesin** [comment]
I have no idea about the use of tools to generate nice PDF.

Personally I prefer to generate flat odf from python and then convert to pdf using libreoffice-headless.
If you are interested in that, drop me a line. Esp. the first part is very convenient.

**Comment by agwisniewska** [comment]
@tabesin Of course, I can use it.

**Comment by agwisniewska** [comment]
https://github.com/fossasia/CommonsNet/pull/44/commits/0722ebdc926a7cfbec49356d2afec006f2d94823

**Comment by agwisniewska** [comment]
I think that I need to divide this issue into two separated ones, because modifying .fodt file has been already done https://github.com/fossasia/CommonsNet/pull/104/commits/fde53c8485f8e2f8022a8c56bacfba036baca591 https://github.com/fossasia/CommonsNet/pull/104/commits/b600262e1fa01a5329eb81884a60d53327fcce6b . Now we need to test it and fix bugs, and then write code to generate pdf file from .fodt file

**Comment by agwisniewska** [comment]
#107
