### ISSUE TITLE
Create CommonsNet Mockups

### ISSUE THREAD

**Issue by mariobehling** [fossasia/CommonsNet#2]
Please state the feature/page and choices for users when they use CommonsNet and create mockups. Upload mockups here and add them into a folder in the repository.

**Comment by agwisniewska** [comment]
@mariobehling @hpdang My version of mockups was added. Please review

**Comment by mariobehling** [comment]
@agwisniewska Any progress on this? There is no point to develop something, if we dont know what is your plan. As usually, we are using GitHub issues for this project.

**Comment by agwisniewska** [comment]
https://github.com/fossasia/CommonsNet/tree/master/mockups it is still available here @mariobehling

**Comment by agwisniewska** [comment]
I dd it some time ago so I hope I can close this issue.
