### ISSUE TITLE
Setup tests, continuous deployments and documentation

### ISSUE THREAD

**Issue by mariobehling** [fossasia/CommonsNet#53]
* [x] Set up code test (travis, codeclimate, codecov, selenium, jenkins, jasmin, phantomjs) and add batches to Readme.md
* [x] Set up development branch that deploys to Heroku and make all commits to development branch first
* [x] Add project info to Readme.md
* [x] Add folder /docs and provide installation instructions and other relevant info

**Comment by mariobehling** [comment]
What is the update on this? In your scrum you write there are difficulties, but we do not see any updates here about what it is. Also, there is no mentioning of Vagrant here and actually it is not really needed. Set up can be done without Vagrant.

**Comment by agwisniewska** [comment]
I use Vagrant to run my local environment, so I think I need to do it on Vagrant. Anyway, I have already solved my trouble. I will add it to GitHub soon.

**Comment by agwisniewska** [comment]
That's it. There are Vagrant + NodeJS + Protractor + Selenium configuration files.   https://github.com/fossasia/CommonsNet/pull/98/commits/a7da16f7d85b6aa76e722659fca784e9b2148787
