### ISSUE TITLE
Add database

### ISSUE THREAD

**Issue by agwisniewska** [fossasia/CommonsNet#87]
We need to add database to CommonsNet website to be able to put collected legal restrictions there.

**Comment by mariobehling** [comment]
I am unclear about this. Why do we need to add another DB? You told us you are working with NodeJS and Angular already. In this case there is no need for another DB, that increases the complexity unnecessarily.

**Comment by agwisniewska** [comment]
I think I need it to be able to collect legal restrictions. Why another DB? I think I use just this one.  I think neither NodeJS nor AngularJS can be databases... Therefore I have chosen Postgres.

**Comment by mariobehling** [comment]
Please list details what kind of legal restrictions you need to collect and save and outline how you need to display it. 

Please describe your choice of technology e.g. Postgres vs. MongoDB.

**Comment by agwisniewska** [comment]
I am not sure now. I need to do research to find out what details I can collect there. But I mean legal restriction of using Internet in different countries. (for e.g. in China you are not able to visit social media like Facebook, or in France you cannot download movies, music or computer games) 

As I've mentioned earlier -  for now I want our users to add them on their own (in case they know how these details are) but later (I mean still in a GSoC time) I want user to simply choose his/her country and all legal restriction will be placed in a form automatically thanks to our collected resources. 

Please take a look at print screen: 
![legal restrictions](https://cloud.githubusercontent.com/assets/16926778/17149756/fdb11624-536c-11e6-8359-c8e47981c2d3.png)

So I need a very simple database like : ( {id: }, {country: },  {list of legal restrictions: } ) (I want to add them manually as I find and confirm them) 

I am not very familiar with any of  these databases. 
The main advantage of Posgres for me is that I have already implemented/added it to CommonsNet repository and it works well on Vagrant. I have spent much time to do it. 

But  on the other hand, I have read some MongoDB tutorials, and it seems to be enough for my needs because you are right I don't need anything complicated. So, even if I have to spend some time to install it, it can make my work easier in the future. So I think I must change my choice.

**Comment by mariobehling** [comment]
For the use case you are mentioning, it might be even sufficient to store the info in JSON files. Please explore this option. An important point is to keep the set up you are creating low maintenance. If you are adding a database, then it needs to be updated and maintained.

Please come up with some samples, that people would actually enter. Please create a separate issue for this.

The way to work should be: 1.) Decide what information you want to store (At the moment you do not seem to have examples.) 2.) Implement according to the requirements outlined in 1).

**Comment by agwisniewska** [comment]
Ok,  2) JSON file has been already implemented. I have also added a sample of information that I want to store 1) https://github.com/fossasia/CommonsNet/pull/111/commits/109ab10cd6523033067492d36ecf624fd4d9e150  
I am not sure if it is very efficient and convient solution, because if it grows up, bugs or difficulties may occur (it is not easy to add new information, and it's not very readable) but for now it's the most efficient and easiest way of implementation for me.

**Comment by agwisniewska** [comment]
As we have decided to implement a login function we need to use a database. We've chosen a MongoDB which works well with nodejs and angularjs

**Comment by agwisniewska** [comment]
https://github.com/fossasia/CommonsNet/pull/125/commits/cc046385b5328ea3cc5f5284539abd080128561d - adding Mongo DB
