### ISSUE TITLE
Name field in contact form is not clickable.

### ISSUE THREAD

**Issue by codebhendi** [fossasia/CommonsNet#93]
In the contact us page(https://commonsnet.herokuapp.com/#/contact) the name field in the form is not clickable.

**Comment by codebhendi** [comment]
I would like to work on this issue.

**Comment by agwisniewska** [comment]
I think @codebhendi that you can do it if you wish.

**Comment by codebhendi** [comment]
ok, thanks

**Comment by agwisniewska** [comment]
Done https://github.com/fossasia/CommonsNet/commit/b8255b05b291b5e1539eabd1fd385b1c71c46c1e
