### ISSUE TITLE
Overflow x not removed in the home page

### ISSUE THREAD

**Issue by codebhendi** [fossasia/CommonsNet#94]
Homepage has some overflow which should be removed.
![overflox](https://cloud.githubusercontent.com/assets/7371972/17208253/7f66fddc-54d5-11e6-9211-ae5ba274e146.jpg)

**Comment by agwisniewska** [comment]
Yes, you are right. But it's been already done, and should be available in a next commit.

**Comment by codebhendi** [comment]
ok cool.

**Comment by agwisniewska** [comment]
https://github.com/fossasia/CommonsNet/pull/92/commits/fd15f1eeb6c4cd727ea686a2da0251a00a11f616 
@codebhendi  done
